[package]
name = "email_machine"
version = "0.1.0"
edition = "2021"

[dependencies]
imap = "3.0.0-alpha.14"
native-tls = "0.2"
config = "0.13"
serde = { version = "1.0", features = ["derive"] }
lettre = { version = "0.10.0-rc.3", features = ["builder", "smtp-transport", "serde"] }