[email]
username = "your_email@example.com"
password = "your_application_specific_password"
sender_email = "sender_email@example.com"
imap_server = "imap.example.com"
imap_port = 993
smtp_server = "smtp.example.com"
smtp_port = 587
